In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
import time
import pandas as pd
from bs4 import BeautifulSoup
import re
import sqlite3

### Scraping Cuenta de Resultados

In [83]:
# Función para limpiar y convertir valores a numéricos
def convertir_a_numerico(valor):
  if isinstance(valor, str):
    # Extraer números, puntos y comas
    valor = re.sub(r'[^\d.,-]', '', valor)
    # Reemplazar comas por puntos si es necesario
    valor = valor.replace(',', '.')
    try:
      return float(valor)
    except ValueError:
      return None
  return valor

def scrap_resultados(tk):
    dfs = []
    driver = webdriver.Chrome()
    try:
        # Abrir la URL
        url = f"https://es.investing.com/equities/{tk}-income-statement"
        driver.get(url)

        # Esperar a que al menos una tabla esté presente
        
        wait = WebDriverWait(driver, 5)
        wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))

        # Obtener el HTML de la página
        page_html = driver.page_source

        # Parsear el HTML de la página con BeautifulSoup
        soup = BeautifulSoup(page_html, "html.parser")

        # Encontrar todas las tablas en la página
        tables = soup.find_all("table")

        # Procesar cada tabla
        for i, table in enumerate(tables):
            # Extraer las filas de la tabla
            rows = table.find_all("tr")
            data = []
            for row in rows:
                cells = row.find_all(["td", "th"])  # Buscar celdas (td) y encabezados (th)
                cell_texts = [cell.get_text(strip=True) for cell in cells]
                data.append(cell_texts)

            # Convertir los datos en un DataFrame de Pandas
            df = pd.DataFrame(data)
            dfs.append(df)
        print("exito al procesar!")

    except TimeoutException:
        print("Error: No se encontraron tablas en la página.")
    except Exception as e:
        print(f"Error: {e}")
    finally:
        # Cerrar el navegador
        driver.quit()
        time.sleep(5)
    return dfs
  
def procesar_tab(df):
  data = pd.DataFrame()
   
  data = df[1].replace("aa.aa",None).reset_index(drop=True)
  data = data.drop(data[data[1]==""].index,axis=0)
  data = data[data[1].notna()]
  data = data.drop(columns=[0])
  data.columns = data.iloc[0]
  data.drop(0,inplace=True,axis=0)
  data = data.dropna(axis=1,how="all")
  data.rename(columns={data.columns[0]:"indicador"},inplace=True)


  # Aplicar la función a todas las columnas excepto 'company'
  ejercicios = [col for col in data.columns if col.startswith("20")]
  for col in ejercicios:  
    data[col] = data[col].apply(convertir_a_numerico)
  
  data.rename(columns=lambda x: x[:4] if x.startswith('20') else x, inplace=True)

  return data.set_index("indicador")

def get_resultados(tk):
  dfs = scrap_resultados(tk)
  if len(dfs) > 0:
    df = procesar_tab(dfs)
    df["company"] = tk
    df["informe"] = "resultados"
    return df
  else:
    return None

### Scraping hoja de Balance (situacion patrimonial)

In [57]:

def scrap_balance_sheet(tk):
    dfs = []
    # Configurar el navegador
    # chrome_options = Options()
    # chrome_options.add_argument("--headless")
    driver = webdriver.Chrome()
    try:
        # Abrir la URL
        url = f"https://es.investing.com/equities/{tk}-balance-sheet"
        driver.get(url)

        # Esperar a que al menos una tabla esté presente
        
        wait = WebDriverWait(driver, 5)
        wait.until(EC.presence_of_element_located((By.TAG_NAME, "table")))

        # Obtener el HTML de la página
        page_html = driver.page_source

        # Parsear el HTML de la página con BeautifulSoup
        soup = BeautifulSoup(page_html, "html.parser")

        # Encontrar todas las tablas en la página
        tables = soup.find_all("table")

        # Procesar cada tabla
        for i, table in enumerate(tables):
            # Extraer las filas de la tabla
            rows = table.find_all("tr")
            data = []
            for row in rows:
                cells = row.find_all(["td", "th"])  # Buscar celdas (td) y encabezados (th)
                cell_texts = [cell.get_text(strip=True) for cell in cells]
                data.append(cell_texts)

            # Convertir los datos en un DataFrame de Pandas
            df = pd.DataFrame(data)
            dfs.append(df)
        print("exito al procesar!")

    except TimeoutException:
        print("Error: No se encontraron tablas en la página.")
    except Exception as e:
        print(f"Error: {e}")
    finally:
        # Cerrar el navegador
        driver.quit()
        time.sleep(5)
    return dfs
  
def procesar_tab(df):
  titulos = df[1].T[0].dropna().reset_index(drop=True).tolist()[1:]
  titulos[0] = "indicador"

  result = pd.DataFrame()
   
  estructura = [
  {"seccion":"activo_corriente", "rubros":2,"valores":3},
  {"seccion":"activo_total", "rubros":4,"valores":5},
  {"seccion":"pasivo_corriente", "rubros":6,"valores":7},
  {"seccion":"pasivo_total", "rubros":8,"valores":9},
  {"seccion":"patrimonio_neto", "rubros":10,"valores":11},
  {"seccion":"crecimiento_deuda", "rubros":14,"valores":15},
]
  for e in estructura:
    try:
      data =  pd.concat([df[e["rubros"]][1],df[e["valores"]]], axis=1)
      data.columns = titulos
      data.replace("aa.aa",None,inplace=True)
      data.dropna(inplace=True, axis=1)
      data["seccion"] = e["seccion"]
      
      result = pd.concat([result, data.reset_index(drop=True)], axis=0)
    except:
      pass
  
    # Aplicar la función a todas las columnas excepto 'company'
  ejercicios = [col for col in result.columns if col.startswith("20")]
  for col in ejercicios:  # se aplica a las columnas de ejercicios
    result[col] = result[col].apply(convertir_a_numerico)
  
  result.rename(columns=lambda x: x[:4] if x.startswith('20') else x, inplace=True)
  
  return result.set_index("indicador")

def get_balance_sheet(tk):
  dfs = scrap_balance_sheet(tk)
  if len(dfs) > 0:
    df = procesar_tab(dfs)
    df["company"] = tk
    df["informe"] = "balance"
    return df
  else:
    return None

### Guardar datos anuales en bbdd

In [53]:
def save_datos_anuales(df):
    # Conectar a la base de datos (o crearla si no existe)
    conn = sqlite3.connect('webmining.db')
    cursor = conn.cursor()
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS datos_anuales (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        company TEXT NOT NULL,
        informe TEXT NOT NULL,
        ejercicio INTEGER NOT NULL,
        indicador TEXT NOT NULL,
        valor REAL
    )
    ''')
    # Insertar datos
    ejercicios = [col for col in df.columns if col.isnumeric()]
    for ejercicio in ejercicios:
        # eliminar los datos para evitar duplicados
        company = df['company'][0]
        informe = df['informe'][0]
        cursor.execute(f"""
                    DELETE FROM datos_anuales 
                    WHERE company = '{company}' AND 
                    informe = '{informe}' AND 
                    ejercicio = {ejercicio}
                    """)
        conn.commit()
        
        # Estructurar e insertar los datos
        df_ej = df[[ejercicio, "company", "informe"]].copy().reset_index()
        df_ej["ejercicio"] = int(ejercicio)
        df_ej.rename(columns={ejercicio: "valor"}, inplace=True)
        df_ej.dropna(subset=["valor"], inplace=True)
        df_ej.to_sql('datos_anuales', conn, if_exists='append', index=False)
        # Guardar los cambios
        conn.commit()
    # Cerrar la conexión
    conn.close()

In [86]:
companies = [
  "apple-computer-inc",
  "microsoft-corp",
  "google-inc",
  "tesla-motors",
  "visa-inc",
  "berkshire-hathaway-inc",
  "johnson-johnson",
  "pfizer",
  "amazon-com-inc",
  "disney",
  "nike",
  "procter-gamble",
  "coca-cola-co",
  "chevron",
  "3m-co"
]

In [87]:
for company in companies:
    print(f"Procesando {company}...")
    try:
        # Procesar los datos
        df_resultados = get_resultados(company)
        if df_resultados is not None:
            save_datos_anuales(df_resultados)
        # df_balance = get_balance_sheet(company)
        # if df_balance is not None:
        #     save_datos_anuales(df_balance)
        print(f"{company} procesado con éxito!")
    except Exception as e:
        print(f"Error al procesar {company}: {e}")

Procesando apple-computer-inc...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

apple-computer-inc procesado con éxito!
Procesando microsoft-corp...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

microsoft-corp procesado con éxito!
Procesando google-inc...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

google-inc procesado con éxito!
Procesando tesla-motors...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

tesla-motors procesado con éxito!
Procesando visa-inc...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

visa-inc procesado con éxito!
Procesando berkshire-hathaway-inc...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

berkshire-hathaway-inc procesado con éxito!
Procesando johnson-johnson...
Error: HTTPConnectionPool(host='localhost', port=63816): Read timed out. (read timeout=120)
johnson-johnson procesado con éxito!
Procesando pfizer...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

pfizer procesado con éxito!
Procesando amazon-com-inc...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

amazon-com-inc procesado con éxito!
Procesando disney...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

disney procesado con éxito!
Procesando nike...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

nike procesado con éxito!
Procesando procter-gamble...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

procter-gamble procesado con éxito!
Procesando coca-cola-co...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

coca-cola-co procesado con éxito!
Procesando chevron...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

chevron procesado con éxito!
Procesando 3m-co...
exito al procesar!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

3m-co procesado con éxito!

C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:19: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  company = df['company'][0]
C:\Users\carre\AppData\Local\Temp\ipykernel_29244\3596493551.py:20: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  informe = df['informe'][0]

In [64]:

# Consultar datos
conn = sqlite3.connect('webmining.db')
cursor = conn.cursor()
cursor.execute("SELECT * FROM datos_anuales WHERE company = '3m-co' AND informe = 'resultados'")
filas = cursor.fetchall()

for fila in filas:
    print(fila)

(3971, '3m-co', 'resultados', 2020, 'Crecmiento total de otros gastos operativos', -2.71)
(3972, '3m-co', 'resultados', 2020, 'Gastos de I+D', 1.862)
(3973, '3m-co', 'resultados', 2020, 'Gastos de venta, generales y administrativos', 6.667)
(3974, '3m-co', 'resultados', 2021, 'Crecmiento total de otros gastos operativos', 3.25)
(3975, '3m-co', 'resultados', 2021, 'Gastos de I+D', 1.994)
(3976, '3m-co', 'resultados', 2021, 'Gastos de venta, generales y administrativos', 6.812)
(3977, '3m-co', 'resultados', 2022, 'Crecmiento total de otros gastos operativos', -20.96)
(3978, '3m-co', 'resultados', 2022, 'Gastos de I+D', 1.16)
(3979, '3m-co', 'resultados', 2022, 'Gastos de venta, generales y administrativos', 5.8)
(3980, '3m-co', 'resultados', 2023, 'Crecmiento total de otros gastos operativos', -21.91)
(3981, '3m-co', 'resultados', 2023, 'Gastos de I+D', 1.123)
(3982, '3m-co', 'resultados', 2023, 'Gastos de venta, generales y administrativos', 4.312)
(3983, '3m-co', 'resultados', 2024, 'Crecmiento total de otros gastos operativos', 7.97)
(3984, '3m-co', 'resultados', 2024, 'Gastos de I+D', 1.07)
(3985, '3m-co', 'resultados', 2024, 'Gastos de venta, generales y administrativos', 4.798)

In [ ]:
conn = sqlite3.connect('webmining.db')
cursor = conn.cursor()
cursor.execute("SELECT COUNT* FROM datos_anuales")
numero_registros = cursor.fetchone()[0]
numero_registros

423

In [85]:
dt = get_resultados("3m-co")
dt

exito al procesar!

,2020,2021,2022,2023,2024,company,informe
indicador,,,,,,,
Ingresos totales,32.184,35.355,26.161,24.610,24.575,3m-co,resultados
Crecimiento de los ingresos totales,0.150,9.850,-26.000,-5.930,-0.140,3m-co,resultados
Coste de los ingresos,16.499,18.795,15.853,14.894,14.417,3m-co,resultados
Beneficio bruto,15.685,16.560,10.308,9.716,10.158,3m-co,resultados
Crecimiento del beneficio bruto,4.070,5.580,-37.750,-5.740,4.550,3m-co,resultados
Margen de beneficio bruto %,48.740,46.840,39.400,39.480,41.330,3m-co,resultados
Total de otros gastos operativos,8.529,8.806,6.960,5.435,5.868,3m-co,resultados
Crecmiento total de otros gastos operativos,NaN,NaN,NaN,NaN,NaN,3m-co,resultados
Gastos de I+D,NaN,NaN,NaN,NaN,NaN,3m-co,resultados
"Gastos de venta, generales y administrativos",NaN,NaN,NaN,NaN,NaN,3m-co,resultados
Otros gastos operativos,NaN,NaN,NaN,NaN,NaN,3m-co,resultados
Margen neto,7.156,7.754,3.348,4.281,4.290,3m-co,resultados
Crecimiento del margen neto,13.500,8.360,-56.820,27.870,0.210,3m-co,resultados
Margen EBIT %,22.230,21.930,12.800,17.400,17.460,3m-co,resultados
Gastos netos por intereses,-500.000,-462.000,-397.000,-691.000,-739.000,3m-co,resultados
Crecimiento de gastos netos por intereses,-35.870,7.600,14.070,-74.060,-6.950,3m-co,resultados
Total de gastos de intereses,-529.000,-488.000,-462.000,-941.000,-1.191,3m-co,resultados
Ingresos por intereses e inversiones,29.000,26.000,65.000,250.000,452.000,3m-co,resultados
Total de otros gastos no operativos,-5.000,10.000,11.000,18.000,9.000,3m-co,resultados
EBT excepto elementos no habituales,6.651,7.302,2.962,3.608,3.560,3m-co,resultados
Ganancia (pérdida) de la venta de activos,389.000,NaN,2.724,36.000,NaN,3m-co,resultados
Total de otras partidas no habituales,NaN,NaN,-1.200,-14.500,NaN,3m-co,resultados
EBT incluyendo las partidas inusuales,6.790,7.214,4.215,-11.253,4.828,3m-co,resultados
Crecimiento del EBT incluidas las partidas inusuales,20.330,6.240,-41.570,-366.980,142.900,3m-co,resultados
Margen del EBT incluidas las partidas inusuales,21.100,20.400,16.110,-45.730,19.650,3m-co,resultados
Impuesto sobre la renta,1.337,1.285,188.000,-2.867,804.000,3m-co,resultados
Beneficios netos para la empresa,5.453,5.929,5.791,-6.979,4.188,3m-co,resultados
Intereses minoritarios,-4.000,-8.000,-14.000,-16.000,-15.000,3m-co,resultados
Beneficio neto,5.449,5.921,5.777,-6.995,4.173,3m-co,resultados
Crecimiento del beneficio neto,20.630,8.660,-2.430,-221.080,159.660,3m-co,resultados
Margen del beneficio neto %,16.930,16.750,22.080,-28.420,16.980,3m-co,resultados
Dividendo preferente y otros ajustes,NaN,NaN,NaN,NaN,NaN,3m-co,resultados
Beneficio neto sobre ingresos ordinarios,5.449,5.921,4.013,-8.402,4.009,3m-co,resultados
BPA básico: Crecimiento de actividades continuadas,9.430,10.230,7.090,-15.170,7.280,3m-co,resultados
BPA básico: crecimiento de actividades continuadas,20.510,8.400,-30.670,-313.940,147.980,3m-co,resultados
BPA diluido: Crecimiento de actividades continuadas,9.360,10.120,7.070,-15.170,7.260,3m-co,resultados
BPA diluido: Actividades continuadas,21.240,8.120,-30.140,-314.570,147.860,3m-co,resultados
Promedio ponderado básico de acciones en circulación,577.600,579.000,566.000,553.900,550.800,3m-co,resultados
Promedio ponderado diluido de acciones en circulación,582.200,585.300,567.600,553.900,552.400,3m-co,resultados
Dividendo por acción,5.880,5.920,5.960,6.000,3.610,3m-co,resultados
Crecimiento del dividendo por acción,2.080,0.680,0.680,0.670,-39.830,3m-co,resultados
EBITDA,9.067,9.669,4.602,5.710,5.470,3m-co,resultados
Crecimiento del EBITDA,14.800,6.640,-52.400,24.080,-4.200,3m-co,resultados
Margen EBITDA %,28.170,27.350,17.590,23.200,22.260,3m-co,resultados
EBIT,7.156,7.754,3.348,4.281,4.290,3m-co,resultados

In [82]:
dt

,2020,2021,2022,2023,2024,seccion,company,informe
indicador,,,,,,,,
Crecmiento total de otros gastos operativos,-2.710,3.250,-20.96,-21.910,7.970,crecimiento_deuda,3m-co,resultados
Gastos de I+D,1.862,1.994,1.16,1.123,1.070,crecimiento_deuda,3m-co,resultados
"Gastos de venta, generales y administrativos",6.667,6.812,5.80,4.312,4.798,crecimiento_deuda,3m-co,resultados
Otros gastos operativos,NaN,NaN,NaN,NaN,NaN,crecimiento_deuda,3m-co,resultados

In [66]:
df = scrap_resultados("3m-co")
df

exito al procesar!

[   0        1     2             3     4       5            6
 0        None  None          None  None    None         None
 1     Símbolo               Bolsa        Divisa         None
 2         MMM          Nueva York           USD  Tiempo real
 3         MMM              México           MXN     Demorada
 4        1MMM               Milán           EUR  Tiempo real
 5         MMM               Suiza           CHF     Demorada
 6         MMM           Fráncfort           EUR     Demorada
 7         MMM               Xetra           EUR     Demorada
 8         MMM           TradeGate           EUR     Demorada
 9        MMMm        Buenos Aires           ARS     Demorada
 10     MMMC34                  B3           BRL     Demorada
 11        MMM               Viena           EUR  Tiempo real,
    0                                    1          2          3          4   \
 0                       Período terminado:  201531/12  201631/12  201731/12
 1                         Ingresos totales      aa.aa      aa.aa      aa.aa
 2                                                None       None       None
 3      Crecimiento de los ingresos totales      aa.aa      aa.aa      aa.aa
 4                                                None       None       None
 .. ..                                  ...        ...        ...        ...
 86                                               None       None       None
 87                         Margen EBITDA %      aa.aa      aa.aa      aa.aa
 88                                               None       None       None
 89                                    EBIT      aa.aa      aa.aa      aa.aa
 90                                               None       None       None

            5          6          7          8          9   ...    40    41  \
 0   201831/12  201931/12  202031/12  202131/12  202231/12  ...  None  None
 1       aa.aa      aa.aa     32.184     35.355     26.161  ...  None  None
 2        None       None       None       None       None  ...  None  None
 3       aa.aa      aa.aa     +0,15%     +9,85%       -26%  ...  None  None
 4        None       None       None       None       None  ...  None  None
 ..        ...        ...        ...        ...        ...  ...   ...   ...
 86       None       None       None       None       None  ...  None  None
 87      aa.aa      aa.aa     28,17%     27,35%     17,59%  ...  None  None
 88       None       None       None       None       None  ...  None  None
 89      aa.aa      aa.aa      7.156      7.754      3.348  ...  None  None
 90       None       None       None       None       None  ...  None  None

       42    43    44    45    46    47    48    49
 0   None  None  None  None  None  None  None  None
 1   None  None  None  None  None  None  None  None
 2   None  None  None  None  None  None  None  None
 3   None  None  None  None  None  None  None  None
 4   None  None  None  None  None  None  None  None
 ..   ...   ...   ...   ...   ...   ...   ...   ...
 86  None  None  None  None  None  None  None  None
 87  None  None  None  None  None  None  None  None
 88  None  None  None  None  None  None  None  None
 89  None  None  None  None  None  None  None  None
 90  None  None  None  None  None  None  None  None

 [91 rows x 50 columns],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
   0                                             1
 0     Crecmiento total de otros gastos operativos
 1                                   Gastos de I+D
 2    Gastos de venta, generales y administrativos
 3                         Otros gastos operativos,
        0      1      2      3      4       5       6        7        8       9
 0  aa.aa  aa.aa  aa.aa  aa.aa  aa.aa  -2,71%  +3,25%  -20,96%  -21,91%  +7,97%
 1  aa.aa  aa.aa  aa.aa  aa.aa  aa.aa   1.862   1.994    1.160    1.123   1.070
 2  aa.aa  aa.aa  aa.aa  aa.aa  aa.aa   6.667   6.812    5.800    4.312   4.798
 3  aa.aa  aa.aa  aa.aa  aa.aa  aa.aa       -       -        -        -       -,
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
 Empty DataFrame
 Columns: []
 Index: [],
                    0       1       2        3
 0             Nombre  Último  % Var.     Vol.
 1          Santander  6,4400  +0,63%   83,90M
 2  Banco de Sabadell  2,7800  +1,39%   27,81M
 3         Telefónica  4,3390  +0,30%   22,12M
 4             Repsol  12,105  +0,33%   10,91M
 5    Cellnex Telecom   32,72  +0,09%    2,29M
 6            Amadeus  74,200  -0,11%    2,09M
 7               Aena  217,60  -0,27%  438,47K,
                 0        1        2        3
 0          Nombre   Último   % Var.     Vol.
 1   Vanadi Coffee     0,03  +43,48%   36,43M
 2   Intercity Sad     0,41  +17,09%    9,68M
 3             DIA  21,4000  +10,31%  214,93K
 4  Cie Automotive   23,700   +5,57%  231,17K
 5     USIMINAS ON    0,960   +5,49%    2,13K
 6         Facephi    2,400   +5,26%   11,87K
 7       Ev Motors     7,56   +5,00%    7,05K,
                           0       1       2        3
 0                    Nombre  Último  % Var.     Vol.
 1  Grupo Financiero Banorte   6,650  -7,64%     0,00
 2               Puig Brands   16,28  -6,97%    6,90K
 3                    Volcan  0,0420  -4,55%   31,10K
 4           Enerside Energy    3,60  -4,26%    4,29K
 5       Lingotes Especiales   6,340  -3,94%    1,80K
 6    Asturiana de Laminados  0,1180  -3,67%  232,98K
 7            Squirrel Media  2,7000  -3,23%   55,13K,
                    0        1        2        3
 0             Nombre   Último   % Var.     Vol.
 1                IAG    3,398   -2,19%   17,29M
 2          Santander   6,4400   +0,63%   83,90M
 3                DIA  21,4000  +10,31%  214,93K
 4              Indra   26,320   -1,42%    1,68M
 5  Banco de Sabadell   2,7800   +1,39%   27,81M,
                      0       1        2                3
 0               Nombre  Último  Al alza  Valor razonable
 1  A Aaa A Aaa A Aa Aa   2,640  +45,88%             3,85
 2        Aaaaaaaaaaaaa   9,700  +30,87%            12,69
 3        Aaaaaa Aa Aaa  16,620  +28,69%            21,39
 4  A Aaaaaaaaaaa Aaaaa  12,105  +28,63%            15,57
 5           A Aa Aaaaa  12,105  +28,63%            15,57
 6                Aaaaa  23,700  +27,97%            30,33
 7        Aaaaa Aaaaaaa  20,300  +22,75%            24,92,
                      0       1        2                3
 0               Nombre  Último  Al alza  Valor razonable
 1  A Aaa A Aaa A Aa Aa   2,640  +45,88%             3,85
 2        Aaaaaaaaaaaaa   9,700  +30,87%            12,69
 3        Aaaaaa Aa Aaa  16,620  +28,69%            21,39
 4  A Aaaaaaaaaaa Aaaaa  12,105  +28,63%            15,57
 5           A Aa Aaaaa  12,105  +28,63%            15,57
 6                Aaaaa  23,700  +27,97%            30,33
 7        Aaaaa Aaaaaaa  20,300  +22,75%            24,92]

In [84]:
dt = procesar_tab(df)
dt

,2020,2021,2022,2023,2024
indicador,,,,,
Ingresos totales,32.184,35.355,26.161,24.610,24.575
Crecimiento de los ingresos totales,0.150,9.850,-26.000,-5.930,-0.140
Coste de los ingresos,16.499,18.795,15.853,14.894,14.417
Beneficio bruto,15.685,16.560,10.308,9.716,10.158
Crecimiento del beneficio bruto,4.070,5.580,-37.750,-5.740,4.550
Margen de beneficio bruto %,48.740,46.840,39.400,39.480,41.330
Total de otros gastos operativos,8.529,8.806,6.960,5.435,5.868
Crecmiento total de otros gastos operativos,NaN,NaN,NaN,NaN,NaN
Gastos de I+D,NaN,NaN,NaN,NaN,NaN
"Gastos de venta, generales y administrativos",NaN,NaN,NaN,NaN,NaN
Otros gastos operativos,NaN,NaN,NaN,NaN,NaN
Margen neto,7.156,7.754,3.348,4.281,4.290
Crecimiento del margen neto,13.500,8.360,-56.820,27.870,0.210
Margen EBIT %,22.230,21.930,12.800,17.400,17.460
Gastos netos por intereses,-500.000,-462.000,-397.000,-691.000,-739.000
Crecimiento de gastos netos por intereses,-35.870,7.600,14.070,-74.060,-6.950
Total de gastos de intereses,-529.000,-488.000,-462.000,-941.000,-1.191
Ingresos por intereses e inversiones,29.000,26.000,65.000,250.000,452.000
Total de otros gastos no operativos,-5.000,10.000,11.000,18.000,9.000
EBT excepto elementos no habituales,6.651,7.302,2.962,3.608,3.560
Ganancia (pérdida) de la venta de activos,389.000,NaN,2.724,36.000,NaN
Total de otras partidas no habituales,NaN,NaN,-1.200,-14.500,NaN
EBT incluyendo las partidas inusuales,6.790,7.214,4.215,-11.253,4.828
Crecimiento del EBT incluidas las partidas inusuales,20.330,6.240,-41.570,-366.980,142.900
Margen del EBT incluidas las partidas inusuales,21.100,20.400,16.110,-45.730,19.650
Impuesto sobre la renta,1.337,1.285,188.000,-2.867,804.000
Beneficios netos para la empresa,5.453,5.929,5.791,-6.979,4.188
Intereses minoritarios,-4.000,-8.000,-14.000,-16.000,-15.000
Beneficio neto,5.449,5.921,5.777,-6.995,4.173
Crecimiento del beneficio neto,20.630,8.660,-2.430,-221.080,159.660
Margen del beneficio neto %,16.930,16.750,22.080,-28.420,16.980
Dividendo preferente y otros ajustes,NaN,NaN,NaN,NaN,NaN
Beneficio neto sobre ingresos ordinarios,5.449,5.921,4.013,-8.402,4.009
BPA básico: Crecimiento de actividades continuadas,9.430,10.230,7.090,-15.170,7.280
BPA básico: crecimiento de actividades continuadas,20.510,8.400,-30.670,-313.940,147.980
BPA diluido: Crecimiento de actividades continuadas,9.360,10.120,7.070,-15.170,7.260
BPA diluido: Actividades continuadas,21.240,8.120,-30.140,-314.570,147.860
Promedio ponderado básico de acciones en circulación,577.600,579.000,566.000,553.900,550.800
Promedio ponderado diluido de acciones en circulación,582.200,585.300,567.600,553.900,552.400
Dividendo por acción,5.880,5.920,5.960,6.000,3.610
Crecimiento del dividendo por acción,2.080,0.680,0.680,0.670,-39.830
EBITDA,9.067,9.669,4.602,5.710,5.470
Crecimiento del EBITDA,14.800,6.640,-52.400,24.080,-4.200
Margen EBITDA %,28.170,27.350,17.590,23.200,22.260
EBIT,7.156,7.754,3.348,4.281,4.290

In [80]:
data = df[1].replace("aa.aa",None).reset_index(drop=True)
data = data.drop(data[data[1]==""].index,axis=0)
data = data[data[1].notna()]
data = data.drop(columns=[0])
data.columns = data.iloc[0]
data.drop(0,inplace=True,axis=0)
data = data.dropna(axis=1,how="all")

# Aplicar la función a todas las columnas excepto 'company'
ejercicios = [col for col in data.columns if col.startswith("20")]
for col in ejercicios:  
  data[col] = data[col].apply(convertir_a_numerico)

data.rename(columns=lambda x: x[:4] if x.startswith('20') else x, inplace=True)

data

,Período terminado:,2020,2021,2022,2023,2024
1,Ingresos totales,32.184,35.355,26.161,24.610,24.575
3,Crecimiento de los ingresos totales,0.150,9.850,-26.000,-5.930,-0.140
5,Coste de los ingresos,16.499,18.795,15.853,14.894,14.417
7,Beneficio bruto,15.685,16.560,10.308,9.716,10.158
9,Crecimiento del beneficio bruto,4.070,5.580,-37.750,-5.740,4.550
11,Margen de beneficio bruto %,48.740,46.840,39.400,39.480,41.330
13,Total de otros gastos operativos,8.529,8.806,6.960,5.435,5.868
15,Crecmiento total de otros gastos operativos,NaN,NaN,NaN,NaN,NaN
16,Gastos de I+D,NaN,NaN,NaN,NaN,NaN
17,"Gastos de venta, generales y administrativos",NaN,NaN,NaN,NaN,NaN
18,Otros gastos operativos,NaN,NaN,NaN,NaN,NaN
23,Margen neto,7.156,7.754,3.348,4.281,4.290
25,Crecimiento del margen neto,13.500,8.360,-56.820,27.870,0.210
27,Margen EBIT %,22.230,21.930,12.800,17.400,17.460
29,Gastos netos por intereses,-500.000,-462.000,-397.000,-691.000,-739.000
31,Crecimiento de gastos netos por intereses,-35.870,7.600,14.070,-74.060,-6.950
33,Total de gastos de intereses,-529.000,-488.000,-462.000,-941.000,-1.191
35,Ingresos por intereses e inversiones,29.000,26.000,65.000,250.000,452.000
37,Total de otros gastos no operativos,-5.000,10.000,11.000,18.000,9.000
39,EBT excepto elementos no habituales,6.651,7.302,2.962,3.608,3.560
41,Ganancia (pérdida) de la venta de activos,389.000,NaN,2.724,36.000,NaN
43,Total de otras partidas no habituales,NaN,NaN,-1.200,-14.500,NaN
45,EBT incluyendo las partidas inusuales,6.790,7.214,4.215,-11.253,4.828
47,Crecimiento del EBT incluidas las partidas inu...,20.330,6.240,-41.570,-366.980,142.900
49,Margen del EBT incluidas las partidas inusuales,21.100,20.400,16.110,-45.730,19.650
51,Impuesto sobre la renta,1.337,1.285,188.000,-2.867,804.000
53,Beneficios netos para la empresa,5.453,5.929,5.791,-6.979,4.188
55,Intereses minoritarios,-4.000,-8.000,-14.000,-16.000,-15.000
57,Beneficio neto,5.449,5.921,5.777,-6.995,4.173
59,Crecimiento del beneficio neto,20.630,8.660,-2.430,-221.080,159.660
61,Margen del beneficio neto %,16.930,16.750,22.080,-28.420,16.980
63,Dividendo preferente y otros ajustes,NaN,NaN,NaN,NaN,NaN
65,Beneficio neto sobre ingresos ordinarios,5.449,5.921,4.013,-8.402,4.009
67,BPA básico: Crecimiento de actividades continu...,9.430,10.230,7.090,-15.170,7.280
69,BPA básico: crecimiento de actividades continu...,20.510,8.400,-30.670,-313.940,147.980
71,BPA diluido: Crecimiento de actividades contin...,9.360,10.120,7.070,-15.170,7.260
73,BPA diluido: Actividades continuadas,21.240,8.120,-30.140,-314.570,147.860
75,Promedio ponderado básico de acciones en circu...,577.600,579.000,566.000,553.900,550.800
77,Promedio ponderado diluido de acciones en circ...,582.200,585.300,567.600,553.900,552.400
79,Dividendo por acción,5.880,5.920,5.960,6.000,3.610
81,Crecimiento del dividendo por acción,2.080,0.680,0.680,0.670,-39.830
83,EBITDA,9.067,9.669,4.602,5.710,5.470
85,Crecimiento del EBITDA,14.800,6.640,-52.400,24.080,-4.200
87,Margen EBITDA %,28.170,27.350,17.590,23.200,22.260
89,EBIT,7.156,7.754,3.348,4.281,4.290